site_name: mkdocs-toc-md
nav:
  - "index.md"
  - "mkdocs-toc-md.md"
  - nest.md: "nestfolder/nest.md"
use_directory_urls: false

theme:
  name: material
  language: en

plugins:
  - toc-md:
      toc_page_title: Contents
      toc_page_description: Usage mkdocs-toc-md
      header_level: 6
      pickup_description_meta: true
      pickup_description_class: true
      output_path: index.md
      output_log: false
      ignore_page_pattern: index.md
      remove_navigation_page_pattern: index.md
      template_dir_path: custom_template

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true

extra_javascript:
  - js/custom.js
extra_css:
  - css/custom.css
