site_name: mkdocs-toc-md
nav:
  - "index.md"
  - "mkdocs-toc-md.md"
use_directory_urls: false

theme:
  name: material
  language: en

plugins:
  - toc-md:
      page_title: Contents
      page_description: Usage mkdocs-toc-md
      pickup_description_meta: true
      pickup_description_class: true
      output_path: index.md
      output_log: true
      ignore_page_pattern: index.md
      remove_navigation_page_pattern: index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true

extra_javascript:
  - js/custom.js
extra_css:
  - css/custom.css
