site_name: mkdocs-toc-md
nav:
  - "index.md"
  - "mkdocs-toc-md.md"
  - nest.md: "nestfolder/nest.md"
  - shift:
    - index: shift/index.md
    - main: shift/shift.md
use_directory_urls: false
repo_url: https://github.com/try0/mkdocs-toc-md
repo_name: mkdocs-toc-md
theme:
  name: material
  language: en  
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
plugins:
  - toc-md:
      toc_page_title: Contents
      toc_page_description: Usage mkdocs-toc-md
      header_level: 6
      pickup_description_meta: true
      pickup_description_class: true
      output_path: index.md
      output_log: false
      ignore_page_pattern: index.*.md
      remove_navigation_page_pattern: index.*.md
      template_dir_path: custom_template
      integrate_mkdocs_static_i18n: true
      languages:
        en:
          toc_page_title: Contents
          toc_page_description: Usage mkdocs-toc-md
        ja:
          toc_page_title: 目次
          toc_page_description: mkdocs-toc-mdプラグインの使い方
      shift_header: after_h1_of_index
      extend_module: true
      output_comment: html
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        ja:
          name: Japanese
          build: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true

extra_javascript:
  - js/custom.js
extra_css:
  - css/custom.css
