import logging
import os
import re
from mkdocs.plugins import BasePlugin
from mkdocs.config import config_options
from bs4 import BeautifulSoup

logging.getLogger(__name__)

class TocMdPlugin(BasePlugin):

    config_scheme = (
        ('pickup_description_meta', config_options.Type(bool, default=False)),
        ('pickup_description_class', config_options.Type(bool, default=False)),
        ('output_path', config_options.Type(str, default='')),
        ('output_log', config_options.Type(bool, default=False)),
        ('ignore_page_pattern', config_options.Type(str, default='')),
        ('remove_navigation_page_pattern', config_options.Type(str, default=True)),
    )

    toc_output_cache = None

    def __init__(self):
        self.logger = logging.getLogger('mkdocs.toc-md')
        self.logger.setLevel(logging.INFO)
        
        self.toc_description_class = 'toc-md-description'


    def on_pre_build(self, config):
        self.logger.info("Enabled Generate toc-md")

    def on_nav(self, nav, config, files):
        # keep navigations
        self.nav = nav


    def on_post_page(self, output_content, page, config):
        
        # remove navigation items
        remove_navigation_page_pattern = re.compile(self.config['remove_navigation_page_pattern'])
        if remove_navigation_page_pattern.match(page.file.src_path):
            print("remove toc")

            soup = BeautifulSoup(output_content, 'html5lib')
            for nav_elm in soup.find_all("nav", {"class": "md-nav md-nav--secondary"}):
                nav_elm.decompose()
    
            souped_html = soup.prettify(soup.original_encoding)
            return souped_html 

        return output_content
        

    def on_post_build(self, config):
        toc_output = ''
        toc_output += '<!-- ====================== TOC ====================== -->\n'
        toc_output += '<!-- Generated by mkdocs-toc-md plugin -->\n'
        toc_output += '<!-- ================================================= -->\n'
        toc_output += '\n'

        ignore_file_pattern = re.compile(self.config['ignore_page_pattern'])

        # Pickup headers
        for page in self.nav.pages:

            if 'output_path' in self.config:
                output_path = self.config['output_path']
                if page.file.src_path == output_path:
                    continue

            ignore = ignore_file_pattern.match(page.file.src_path)
            if ignore:
                continue

            soup = BeautifulSoup(page.content, 'html5lib')

            toc_description = ''
            if 'pickup_description_meta' in self.config:
                if self.config['pickup_description_meta']:
                    description_elm = soup.find('meta', attrs={'name':'description'})
                    if description_elm is not None:
                        toc_description += description_elm['content']

            if 'pickup_description_class' in self.config:
                if self.config['pickup_description_class']:
                    description_elm = soup.find(True, class_=self.toc_description_class)
                    if description_elm is not None:
                        toc_description += description_elm.text


            article_headers = soup.find_all(['h1', 'h2', 'h3'])
            for h in article_headers:

                text = h.text
                if h.name == 'h1':
                    toc_output += '\n\n## ' + h.text

                    if toc_description:
                        toc_output += '\n' + toc_description + '\n'
                elif h.name == 'h2':
                    toc_output += '\n### [' + h.text + '](' + page.file.src_path + '#' + h.get('id') + ')\n'
                elif h.name == 'h3' :
                    toc_output += '* [' + h.text + '](' + page.file.src_path + '#' + h.get('id') + ')\n'
                else:
                    continue



        # print to console
        if 'output_log' in self.config:
            if self.config['output_log']:
                print(toc_output)

        if 'output_path' in self.config:
            output_path = self.config['output_path']
            if output_path and toc_output != TocMdPlugin.toc_output_cache:
                abs_md_path = os.path.join(config['docs_dir'], output_path)
                os.makedirs(os.path.dirname(abs_md_path), exist_ok=True)

                self.logger.info(f'Output a toc.md to "{abs_md_path}".')

                mode = 'x'
                if os.path.isfile(abs_md_path):
                    mode = 'w'
                file = open(abs_md_path, mode, encoding='utf-8')
                file.write(toc_output)
                file.close()

                # avoid infinite loop
                TocMdPlugin.toc_output_cache = toc_output


