from pathlib import Path
import sys
import logging
import os
import posixpath
import re
from collections import OrderedDict
from typing import TYPE_CHECKING, Any, Iterator, List, Mapping, Optional, Type, TypeVar, Union
from mkdocs import plugins
from mkdocs.plugins import BasePlugin
from mkdocs.config import config_options
from mkdocs.structure.pages import Page
from mkdocs.structure.nav import Navigation, Section, Link
from mkdocs_toc_md.objects import TocConfig, TocItem, TocPageData
from mkdocs_toc_md.hook import TocExtendModule
from bs4 import BeautifulSoup
from jinja2 import Environment, FileSystemLoader, TemplateNotFound
try:
    from mkdocs.plugins import event_priority
except ImportError:
    def event_priority(priority): return lambda f: f  # No-op fallback


logging.getLogger(__name__)


class TocMdPlugin(BasePlugin):
    TEMPLATE_NAME = 'toc.md.j2'
    SUBDIR_BASE_TEMPLATE_NAME = 'toc.subdir.md.j2'
    GENERATED_MARKER_TEXT = 'Generated by mkdocs-toc-md plugin'

    config_scheme = (
        ('pickup_description_meta', config_options.Type(bool, default=False)),
        ('pickup_description_class', config_options.Type(bool, default=False)),
        ('output_path', config_options.Type(str, default='index.md')),
        ('output_root_index', config_options.Type(bool, default=True)),
        ('subdir_index_depth', config_options.Type(int, default=0)),
        ('overwrite', config_options.Choice(('generated', 'always', 'never'), default='always')),
        ('output_log', config_options.Type(bool, default=False)),
        ('ignore_page_pattern', config_options.Type(str, default='')),
        ('remove_navigation_page_pattern', config_options.Type(str, default='')),
        ('toc_page_title', config_options.Type(str, default='Contents')),
        ('toc_page_description', config_options.Type(str, default=None)),
        ('header_level', config_options.Type(int, default=3)),
        ('template_dir_path', config_options.Type(str, default=None)),
        ('beautiful_soup_parser', config_options.Type(str, default='html.parser')),
        ('languages', config_options.Type(dict, default=dict())),
        ('integrate_mkdocs_static_i18n', config_options.Type(bool, default=False)),
        ('extend_module', config_options.Type(bool, default=False)),
        ('shift_header', config_options.Type(str, default='none')),
        ('output_comment', config_options.Type(str, default='html')),
    )

    def __init__(self):
        self.logger = logging.getLogger('mkdocs.toc-md')
        self.logger.setLevel(logging.INFO)

        self.toc_description_class = 'toc-md-description'
        self.is_build_command = 'build' in sys.argv

    def on_pre_build(self, config):
        self.logger.info("Enabled toc-md plugin")

        self.toc_config = TocConfig(config, self.config)

        self.toc_output_comment = self.toc_config.get_output_comment()

        # mkdocs-static-i18n
        self.i18n_plugin = None
        if self.config['integrate_mkdocs_static_i18n'] and 'i18n' in config['plugins']:
            self.i18n_plugin = config['plugins']['i18n']

        self.hook = TocExtendModule(self.toc_config)

    def on_serve(self, server, config, builder):
        # for dev
        try:
            TocExtendModule.watch_file(server, builder)

            if 'output_path' in self.config:
                output_path = self.config['output_path']
                if self.i18n_plugin:
                    for lang in self.i18n_plugin.i18n_navs:
                        output_path_i18n = re.sub('md$', lang + '.md', output_path)
                        if os.path.exists(output_path_i18n):
                            server.watch(output_path_i18n, builder)
                else:
                    if os.path.exists(output_path):
                        server.watch(output_path, builder)
        except Exception as e:
            self.logger.error('toc-md: Failed watch files', e)

    def on_nav(self, nav: Navigation, config, files):
        # keep navigations
        self.nav = nav


    def on_post_page(self, output_content, page, config):
        # remove navigation items
        pattern = self.config['remove_navigation_page_pattern']
        if pattern:
            remove_navigation_page_re = re.compile(pattern)
            if remove_navigation_page_re.match(page.file.src_path):
                self.logger.info("toc-md: Remove toc")

                soup = BeautifulSoup(
                    output_content, self.config['beautiful_soup_parser'])
                for nav_elm in soup.find_all("nav", {"class": "md-nav md-nav--secondary"}):
                    nav_elm.decompose()

                souped_html = soup.prettify(soup.original_encoding)
                return souped_html

        return output_content

    @plugins.event_priority(-100)
    def on_post_build(self, config):

        ignore_file_pattern = self.config['ignore_page_pattern']
        self.ignore_re = None
        if ignore_file_pattern:
            self.ignore_re = re.compile(ignore_file_pattern)

        self.header_names = []
        for level in range(self.config['header_level']):
            self.header_names.append('h' + str(level + 1))

        self.logger.info('toc-md: Lookup ' + ', '.join(self.header_names))

        if self.i18n_plugin:
            # mkdocs-static-i18n
            # https://github.com/ultrabug/mkdocs-static-i18n

            for lang in self.i18n_plugin.i18n_navs:
                use_folder = 'folder' == self.i18n_plugin.config['docs_structure']
                nav = self.i18n_plugin.i18n_navs[lang]
                if use_folder:
                    self.output(config, nav, "", lang)
                else:
                    self.output(config, nav, lang, "")

        else:
            # default

            self.output(config, self.nav, "", "")

    def create_toc_items(
            self,
            toc_items,
            nav_item: Union[Page, Section, Link],
            config,
            lang,
            nav_item_depth,
            target_dir=None,
            output_src_path=None):

        if nav_item.is_link and not nav_item.is_page:
            # no page file
            return
        
        if nav_item.is_section and not nav_item.is_page:
            # no page file
            if self.config['shift_header'] and not self.config['shift_header'] == 'none':
                # consider nav hierarchy
                nav_item_depth += 1

            for child_item in nav_item.children:
                self.create_toc_items(
                    toc_items,
                    child_item,
                    config,
                    lang,
                    nav_item_depth,
                    target_dir,
                    output_src_path)
            return

        # page file

        page = nav_item
        page_src_path = self.normalize_src_path(page.file.src_path)
        if output_src_path and page_src_path == output_src_path:
            return

        if target_dir and not self.is_under_directory(page_src_path, target_dir):
            return

        ignore = self.ignore_re and self.ignore_re.match(
            page.file.src_path)
        if ignore:
            return

        soup = BeautifulSoup(
            page.content, self.config['beautiful_soup_parser'])

        # extract page description
        toc_description = ''
        if 'pickup_description_meta' in self.config:
            if self.config['pickup_description_meta']:
                description_elm = soup.find(
                    'meta', attrs={'name': 'description'})
                if description_elm is not None:
                    toc_description += description_elm['content']

        if 'pickup_description_class' in self.config:
            if self.config['pickup_description_class']:
                description_elm = soup.find(
                    True, class_=self.toc_description_class)
                if description_elm is not None:
                    toc_description += description_elm.text

        if 'toc_md_description' in page.meta:
            toc_description += page.meta['toc_md_description']

        # create TocItem
        src_elements = []
        if self.use_extend_module('find_src_elements'):
            # user impl
            src_elements = self.hook.find_src_elements(soup, page)
        else:
            # default
            src_elements = soup.find_all(self.header_names)

        if self.use_extend_module('create_toc_items'):
            # user impl
            items = self.hook.create_toc_items(
                page, toc_description, src_elements)
            if target_dir:
                for item in items:
                    if item.url:
                        item.url = self.to_relative_url(item.url, target_dir)
            toc_items.extend(items)
        else:
            # default
            for elm in src_elements:

                toc_header = TocItem()
                if elm.find('a', attrs={'class', 'headerlink'}):
                    elm.a.extract()

                toc_header.text = elm.text

                if elm.has_attr("id"):
                    toc_header.url = self.to_relative_url(
                        page_src_path + '#' + elm.get('id'),
                        target_dir)
                else:
                    toc_header.url = self.to_relative_url(
                        page_src_path,
                        target_dir)
                    self.logger.warning(
                        'toc-md: Cannot generate URL with hash property because the target element has no id attribute.')
                    
                if elm.name == 'h1':
                    toc_header.src_level = 1
                    if toc_description:
                        toc_header.description = toc_description
                elif elm.name == 'h2':
                    toc_header.src_level = 2
                elif elm.name == 'h3':
                    toc_header.src_level = 3
                elif elm.name == 'h4':
                    toc_header.src_level = 4
                elif elm.name == 'h5':
                    toc_header.src_level = 5
                elif elm.name == 'h6':
                    toc_header.src_level = 6

                toc_header.level = (toc_header.src_level + nav_item_depth)

                if self.config['shift_header'] and not self.config['shift_header'] == 'none':
                    index_re = re.compile('.*(index.' + lang + '.md$|index.md$)')
                    if self.config['shift_header'] == 'after_h1':
                        if index_re.match(page.file.src_path):
                            toc_header.level -= 1
                    elif self.config['shift_header'] == 'after_h1_of_index':
                        if index_re.match(page.file.src_path) and toc_header.src_level == 1:
                            toc_header.level -= 1

                if self.use_extend_module('on_create_toc_item'):
                    # user hook
                    self.hook.on_create_toc_item(toc_header, elm, page)
                toc_items.append(toc_header)

    def output(self, config, nav, lang, folder):

        if self.config['output_root_index']:
            root_output_path = self.get_output_path(lang)
            root_output_src_path = self.normalize_src_path(root_output_path)

            toc_headers = self.create_output_toc_headers(
                nav,
                config,
                lang,
                None,
                root_output_src_path)

            self.output_toc_md_file(
                config,
                nav,
                toc_headers,
                lang,
                folder,
                None)

        self.output_subdir_indexes(config, nav, lang, folder)

    def create_output_toc_headers(self, nav, config, lang, target_dir, output_src_path):
        """ Pickup headers for one output markdown file. """

        toc_headers = []
        nav_item_depth = 1
        for nav_item in nav.items:
            self.create_toc_items(
                toc_headers,
                nav_item,
                config,
                lang,
                nav_item_depth,
                target_dir,
                output_src_path)
        return toc_headers

    def output_toc_md_file(self, config, nav, toc_headers, lang, folder, target_dir):
        """ Render and write one table of contents markdown file. """

        if self.use_extend_module('on_before_output'):
            # user hook
            self.hook.on_before_output(nav, toc_headers)

        # create template arg
        template_param = TocPageData()
        template_param.page_title = self.config['toc_page_title']
        if lang in self.config['languages']:
            if 'toc_page_title' in self.config['languages'][lang]:
                template_param.page_title = self.config['languages'][lang]['toc_page_title']

        template_param.page_description = self.config['toc_page_description']
        if lang in self.config['languages']:
            if 'toc_page_description' in self.config['languages'][lang]:
                template_param.page_description = self.config['languages'][lang]['toc_page_description']

        template_param.toc_headers = toc_headers
        template_param.toc_output_comment = self.toc_output_comment
        template_param.is_subdir_index = target_dir is not None
        template_param.directory_path = target_dir
        template_param.directory_name = posixpath.basename(target_dir) if target_dir else None
        template_param.directory_depth = self.get_directory_depth(target_dir)

        if target_dir:
            template_param.page_title = template_param.directory_name

        self.output_md_file(config, template_param, lang, folder, target_dir)

    def output_subdir_indexes(self, config, nav, lang, folder):
        """ Outputs index markdown files under nav-backed subdirectories. """

        depth = self.config['subdir_index_depth']
        if depth <= 0:
            return

        target_dirs = self.collect_subdir_index_dirs(nav, depth)
        if not target_dirs:
            return

        output_file_name = posixpath.basename(self.get_output_path(lang))
        for target_dir in target_dirs:
            output_src_path = self.join_src_path(target_dir, output_file_name)
            toc_headers = self.create_output_toc_headers(
                nav,
                config,
                lang,
                target_dir,
                output_src_path)

            if not toc_headers:
                self.logger.info(
                    f'toc-md: Skip empty subdirectory toc markdown file for "{target_dir}".')
                continue

            self.output_toc_md_file(
                config,
                nav,
                toc_headers,
                lang,
                folder,
                target_dir)

    def output_md_file(self, config, template_param, file_suffix, append_folder, target_dir=None):
        """ Outputs markdown file. """

        template_path = self.get_template_paths()

        # using custom template
        if 'template_dir_path' in self.config:
            if self.config['template_dir_path'] and os.path.exists(self.config['template_dir_path']):
                self.logger.info("toc-md: Use custom template")

        # render contents
        jinja_env = Environment(
            loader=FileSystemLoader(template_path),
            trim_blocks=True
        )
        template = self.get_template(jinja_env, target_dir)
        toc_output = template.render(data=template_param)

        # print to console
        if 'output_log' in self.config:
            if self.config['output_log']:
                print(toc_output)

        # save file
        if 'output_path' in self.config:
            output_path = self.get_output_path(file_suffix)
            if target_dir:
                output_path = self.join_src_path(
                    target_dir,
                    posixpath.basename(output_path))

            if output_path:
                abs_md_path = os.path.join(
                    config['docs_dir'], append_folder, *output_path.split('/'))
                os.makedirs(os.path.dirname(abs_md_path), exist_ok=True)

                # avoid infinite loop
                if os.path.isfile(abs_md_path):
                    with open(abs_md_path, 'r', encoding='utf-8') as file:
                        old_content = file.read()
                        if old_content == toc_output:
                            self.logger.info(f'toc-md: No changes')
                            return

                        if not self.can_overwrite(old_content, abs_md_path):
                            return

                mode = 'x'
                if os.path.isfile(abs_md_path):
                    mode = 'w'

                with open(abs_md_path, mode, encoding='utf-8') as file:
                    file.write(toc_output)

                self.logger.info(
                    f'toc-md: Output a toc markdown file to "{abs_md_path}".')

                if self.is_build_command:
                    self.logger.warning(
                        'toc-md: Command line contains [build]. You may need to build again to render toc md as html.')

    def use_extend_module(self, name) -> bool:
        return 'extend_module' in self.config and self.config['extend_module'] and self.hook.can_call(name)

    def get_output_path(self, file_suffix):
        output_path = self.config['output_path']
        if file_suffix:
            output_path = re.sub('md$', file_suffix + '.md', output_path)
        return self.normalize_src_path(output_path)

    def get_template_paths(self):
        base_path = os.path.abspath(os.path.dirname(__file__))
        template_path = [os.path.join(base_path, 'template')]

        if 'template_dir_path' in self.config:
            if self.config['template_dir_path'] and os.path.exists(self.config['template_dir_path']):
                template_path = [self.config['template_dir_path']]

        return template_path

    def get_template(self, jinja_env, target_dir=None):
        for template_name in self.get_template_name_candidates(target_dir):
            try:
                return jinja_env.get_template(template_name)
            except TemplateNotFound:
                continue

        return jinja_env.get_template(self.TEMPLATE_NAME)

    def get_template_name_candidates(self, target_dir=None):
        template_names = []

        if target_dir:
            parent_dir_name = posixpath.basename(target_dir)
            template_names.append('toc.subdir.' + parent_dir_name + '.md.j2')
            template_names.append(self.SUBDIR_BASE_TEMPLATE_NAME)

        template_names.append(self.TEMPLATE_NAME)

        # Remove duplicates without requiring Python 3.7+ dict ordering.
        unique_template_names = []
        for template_name in template_names:
            if template_name not in unique_template_names:
                unique_template_names.append(template_name)

        return unique_template_names

    def can_overwrite(self, old_content, abs_md_path):
        overwrite = self.config['overwrite']
        if overwrite == 'always':
            return True

        if overwrite == 'never':
            self.logger.info(
                f'toc-md: Skip existing toc markdown file because overwrite is "never": "{abs_md_path}".')
            return False

        if self.GENERATED_MARKER_TEXT in old_content:
            return True

        self.logger.info(
            f'toc-md: Skip existing toc markdown file without generated marker: "{abs_md_path}".')
        return False

    def collect_subdir_index_dirs(self, nav, max_depth):
        target_dirs = OrderedDict()

        for page in self.iter_nav_pages(nav.items):
            src_path = self.normalize_src_path(page.file.src_path)
            if not self.is_markdown_path(src_path):
                continue

            parent_dir = posixpath.dirname(src_path)
            if not parent_dir:
                continue

            parts = parent_dir.split('/')
            limit_depth = min(max_depth, len(parts))
            for depth in range(1, limit_depth + 1):
                target_dir = '/'.join(parts[:depth])
                target_dirs[target_dir] = True

        return list(target_dirs.keys())

    def iter_nav_pages(self, nav_items):
        for nav_item in nav_items:
            if nav_item.is_link and not nav_item.is_page:
                continue

            if nav_item.is_section and not nav_item.is_page:
                for page in self.iter_nav_pages(nav_item.children):
                    yield page
                continue

            yield nav_item

    def normalize_src_path(self, src_path):
        return src_path.replace('\\', '/').strip('/')

    def is_markdown_path(self, src_path):
        path_without_fragment = src_path.split('#', 1)[0].lower()
        return path_without_fragment.endswith('.md') or path_without_fragment.endswith('.markdown')

    def is_under_directory(self, src_path, target_dir):
        target_dir = self.normalize_src_path(target_dir)
        src_path = self.normalize_src_path(src_path)
        return src_path.startswith(target_dir + '/')

    def to_relative_url(self, url, target_dir=None):
        if not target_dir:
            return url

        path, sep, fragment = url.partition('#')
        relative_path = posixpath.relpath(path, target_dir)
        if sep:
            return relative_path + sep + fragment

        return relative_path

    def join_src_path(self, *parts):
        clean_parts = []
        for part in parts:
            normalized_part = self.normalize_src_path(part)
            if normalized_part:
                clean_parts.append(normalized_part)

        return '/'.join(clean_parts)

    def get_directory_depth(self, target_dir):
        if not target_dir:
            return 0

        return len(self.normalize_src_path(target_dir).split('/'))


