import logging
import os
import re
from mkdocs.plugins import BasePlugin
from mkdocs.config import config_options
from bs4 import BeautifulSoup

from jinja2 import Environment, FileSystemLoader

logging.getLogger(__name__)


class TocData:
    level = 1
    text  = None
    description = None
    link = None

    def get_md_header_prefix(self):
        """ Gets level as markdown header.

        """

        prefix = '#'
        for num in range(self.level):
            prefix += '#'
        return prefix

    def get_md_header(self):
        """ Gets text as markdown header.

        """

        prefix = self.get_md_header_prefix()

        if self.link:
            return prefix + ' [' + self.text + '](' + self.link + ')'

        return prefix + ' ' + self.text
        
        

    def get_md_ul_item(self):
        """ Gets text as markdown list item.

        """

        if self.link:
            return '* [' + self.text + '](' + self.link + ')'
        
        return '* ' + self.text

    def has_description(self):
        return self.description is not None 



class TocMdPlugin(BasePlugin):

    config_scheme = (
        ('pickup_description_meta', config_options.Type(bool, default=False)),
        ('pickup_description_class', config_options.Type(bool, default=False)),
        ('output_path', config_options.Type(str, default='')),
        ('output_log', config_options.Type(bool, default=False)),
        ('ignore_page_pattern', config_options.Type(str, default='')),
        ('remove_navigation_page_pattern', config_options.Type(str, default='')),
        ('page_title', config_options.Type(str, default='Contents')),
        ('page_description', config_options.Type(str, default=None)),
        ('template_path', config_options.Type(str, default=None)),
    )

    toc_output_cache = None

    def __init__(self):
        self.logger = logging.getLogger('mkdocs.toc-md')
        self.logger.setLevel(logging.INFO)
        
        self.toc_description_class = 'toc-md-description'

        self.toc_output_comment = ''
        self.toc_output_comment += '<!-- ====================== TOC ====================== -->\n'
        self.toc_output_comment += '<!-- Generated by mkdocs-toc-md plugin -->\n'
        self.toc_output_comment += '<!-- ================================================= -->\n'
        self.toc_output_comment += '\n'


    def on_pre_build(self, config):
        self.logger.info("Enabled Generate toc-md")

    def on_nav(self, nav, config, files):
        # keep navigations
        self.nav = nav


    def on_post_page(self, output_content, page, config):
        
        # remove navigation items
        remove_navigation_page_pattern = re.compile(self.config['remove_navigation_page_pattern'])
        if remove_navigation_page_pattern.match(page.file.src_path):
            print("remove toc")

            soup = BeautifulSoup(output_content, 'html5lib')
            for nav_elm in soup.find_all("nav", {"class": "md-nav md-nav--secondary"}):
                nav_elm.decompose()
    
            souped_html = soup.prettify(soup.original_encoding)
            return souped_html 

        return output_content
        

    def on_post_build(self, config):


        ignore_file_pattern = re.compile(self.config['ignore_page_pattern'])

        # Pickup headers
        for page in self.nav.pages:

            if 'output_path' in self.config:
                output_path = self.config['output_path']
                if page.file.src_path == output_path:
                    continue

            ignore = ignore_file_pattern.match(page.file.src_path)
            if ignore:
                continue

            soup = BeautifulSoup(page.content, 'html5lib')

            toc_description = ''
            if 'pickup_description_meta' in self.config:
                if self.config['pickup_description_meta']:
                    description_elm = soup.find('meta', attrs={'name':'description'})
                    if description_elm is not None:
                        toc_description += description_elm['content']

            if 'pickup_description_class' in self.config:
                if self.config['pickup_description_class']:
                    description_elm = soup.find(True, class_=self.toc_description_class)
                    if description_elm is not None:
                        toc_description += description_elm.text

            toc_headers = []
            article_headers = soup.find_all(['h1', 'h2', 'h3'])
            for h in article_headers:

                toc_header = TocData()
                if h.find('a', attrs={'class', 'headerlink'}):
                     h.a.extract()

                toc_header.text = h.text
                toc_header.link = page.file.src_path + '#' + h.get('id')

                if h.name == 'h1':
                    toc_header.level = 1
                    if toc_description:
                        toc_header.description = toc_description
                elif h.name == 'h2':
                    toc_header.level = 2
                elif h.name == 'h3' :
                    toc_header.level = 3
                elif h.name == 'h4' :
                    toc_header.level = 4
                elif h.name == 'h5' :
                    toc_header.level = 5
                elif h.name == 'h6' :
                    toc_header.level = 6

                toc_headers.append(toc_header)

        # render contents
        base_path = os.path.abspath(os.path.dirname(__file__))
        template_path = [os.path.join(base_path, 'template')]

        # using custom template
        if 'template_path' in self.config:
            if self.config['template_path'] and os.path.isfile(self.config['template_path']):
                template_path = self.config['template_path']

        jinja_env = Environment(
            loader = FileSystemLoader(template_path),
            trim_blocks = True
        )

        template = jinja_env.get_template('default_toc.md.j2')
        toc_output = template.render(
            page_title = self.config['page_title'],
            page_description = self.config['page_description'],
            toc_headers = toc_headers,
            toc_output_comment = self.toc_output_comment)

        # print to console
        if 'output_log' in self.config:
            if self.config['output_log']:
                print(toc_output)

        if 'output_path' in self.config:
            output_path = self.config['output_path']
            if output_path and toc_output != TocMdPlugin.toc_output_cache:
                abs_md_path = os.path.join(config['docs_dir'], output_path)
                os.makedirs(os.path.dirname(abs_md_path), exist_ok=True)

                self.logger.info(f'Output a toc.md to "{abs_md_path}".')

                mode = 'x'
                if os.path.isfile(abs_md_path):
                    mode = 'w'
                file = open(abs_md_path, mode, encoding='utf-8')
                file.write(toc_output)
                file.close()

                # avoid infinite loop
                TocMdPlugin.toc_output_cache = toc_output



